language: php
php:
  - 7.1

before_script:
  - git clone https://github.com/nikic/php-ast.git
  - cd php-ast
  - phpize
  - ./configure
  - make
  - make install
  - cd ..
  - phpenv config-add travisphp.ini
  - composer install

script: phpunit --configuration quality/phpunit.xml --coverage-text
